#!/usr/bin/env python2

from mr_repo import MrRepo

if __name__ == '__main__':
    from sys import argv
    import re
    prog = "mr_repo"
    if (len(argv) > 0):
        prog = argv.pop(0)
        # If prog does not look something like Mr. Repo then change it
        if None == re.search('mr(\.|)([-_ ]{0,2})repo', prog,
                flags=re.IGNORECASE):
            prog = "mr_repo"
    #Create an instance of MrRepo
    repomr = MrRepo(prog=prog, args=argv, execute=True, one_use=True)
